name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install CDK
        run: |
          npm install -g aws-cdk@1.94.1
      - name: Install Dependencies
        run: |
          npm install
      - name: Ls
        run: |
          ls
      - name: Pull in Lambdas
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ServerBoiTeam/Discord-Slash-Command-Lambdas
      - name: Ls
        run: |
          ls
      - name: CDK Deploy
        run: |
          npm run build
          cdk deploy --all --require-approval never
        env:
          AWS_REGION: ${{ secrets.REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
