name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install CDK
        run: |
          npm install -g aws-cdk@1.94.1
      - name: Install Dependencies
        run: |
          npm install
      - name: Create Lambda Package Dir
        run: |
          mkdir lambda_packages
      - name: Pull in Lambdas
        uses: dawidd6/action-download-artifact@v2
        with:
          # Optional, GitHub token, a Personal Access Token with `public_repo` scope if needed
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build_zips.yml
          workflow_conclusion: success
          branch: main
          event: push
          path: lambda_packages/
          # Optional, defaults to current repo
          repo: https://github.com/ServerBoiTeam/Discord-Slash-Command-Lambdas
      - name: CDK Deploy
        run: |
          npm run build
          cdk deploy --all --require-approval never
        env:
          AWS_REGION: ${{ secrets.REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
