name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install CDK
        run: |
          npm install -g aws-cdk@1.94.1
      - name: Install Dependencies
        run: |
          npm install
      - name: Download function uri list
        run: aws s3 cp s3://serverboi-sam-packages/function_uri_list.json function_uri_list.json
      - name: CDK Deploy
        run: |
          npm run build
          cdk deploy --all --require-approval never
