name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install CDK
        run: |
          npm install -g aws-cdk@1.94.1
      - name: Install Dependencies
        run: |
          npm install
      - name: Pull in Lambdas
        run: |
          mkdir lambda_packages
          git clone https://github.com/ServerBoiTeam/Discord-Slash-Command-Lambdas.git lambda_packages
          cd lambda_packages
          for d in */ ; do echo "$d" && cd $d/lambda && npm install && npm run compile && ls && cd ../.. ; done
      - name: CDK Deploy
        run: |
          npm run build
          cdk deploy --all --require-approval never
        env:
          AWS_REGION: ${{ secrets.REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
